---
outdir: 'mlp_8bit_8const'
data_hyperparams:
  root: '../data/jetid'
  nconst: 8
  feats: "ptetaphi"
  norm: "robust"
  kfolds: 5
  seed: 511

model_type: "qmlp_reg"
model_hyperparams:
  layers: [120, 60, 32, 64, 64, 64, 32, 44]
  activ: "relu"
  l1_coeff: 0.0000131
  nbits: 8
  output_dim: 5

compilation_hyperparams:
  optimizer: "adam"
  optimizer_hps:
    learning_rate: 0.0013
  optimizer_callbacks:
    early_stopping:
      monitor: "val_categorical_accuracy"
      patience: 20
    lr_decay:
      monitor: "val_categorical_accuracy"
      factor: 0.8
      patience: 10
      min_lr: 0.0001

  loss: "softmax_with_crossentropy"
  metrics: ["categorical_accuracy"]
  early_stopping: 20

training_hyperparams:
  batch_size: 128
  epochs: 1000
  shuffle: True
  verbose: 2
