---
outdir: 'deepsets_14bit_8const'
data_hyperparams:
  root: '../data/jetid'
  nconst: 8
  feats: "ptetaphi"
  norm: "robust"
  kfolds: 5
  seed: 511

model_type: "qinvariant"
model_hyperparams:
  phi_layers: [32, 32, 32]
  rho_layers: [32]
  activ: "relu"
  aggreg: "mean"
  output_dim: 5
  nbits: 14

compilation_hyperparams:
  optimizer: "adam"
  optimizer_hps:
    learning_rate: 0.0018
  optimizer_callbacks:
    early_stopping:
      monitor: "val_categorical_accuracy"
      patience: 20
    lr_decay:
      monitor: "val_categorical_accuracy"
      factor: 0.8
      patience: 10
      min_lr: 0.0001

  loss: "softmax_with_crossentropy"
  metrics: ["categorical_accuracy"]
  early_stopping: 20

training_hyperparams:
  batch_size: 256
  epochs: 1000
  shuffle: True
  verbose: 2
